# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Solana
export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

# Local binaries
export PATH="$HOME/.local/bin:$PATH"
